version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: dcat_backend
  #   ports:
  #     - "2000:2000"
  #   env_file:
  #     - .env
  #   environment:
  #     DB_HOST: postgres
  #     DB_NAME: ${APP_DB_NAME:-app_db_name}
  #     DB_USER: ${APP_DB_USER:-app_db_user}
  #     DB_PASSWORD: ${APP_DB_PASSWORD:-app_db_password}
  #   depends_on:
  #     - postgres
  #     - keycloak
  #   networks:
  #     - dcat_network

  postgres:
    image: postgres:15-alpine
    container_name: dcat_postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_postgres_password}
      POSTGRES_USER: ${POSTGRES_USER:-default_postgres_user}
      # POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./.env:/tmp/.env:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dcat_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    env_file: .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME:-keycloak_db}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak_user}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak123}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin123}
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KC_HEALTH_ENABLED: true
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["start-dev"]
    networks:
      - dcat_network

volumes:
  postgres_data:

networks:
  dcat_network:
    driver: bridge






# version: '3.8'

# services:
#   postgres:
#     image: postgres:15-alpine
#     container_name: dcat_postgres
#     env_file: .env
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_postgres_password}
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./init-db:/docker-entrypoint-initdb.d
#       - ./.env:/tmp/.env:ro
#     ports:
#       - "${DB_PORT:-5432}:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
#     networks:
#       - dcat_network

#   keycloak:
#     image: quay.io/keycloak/keycloak:26.1.4
#     container_name: keycloak
#     env_file: .env
#     volumes:
#       - ./keycloak-extensions:/opt/keycloak/providers
#     environment:
#       KC_DB: postgres
#       KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME:-keycloak_db}
#       KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak_user}
#       KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak123}
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin123}
#       KC_HTTP_ENABLED: "true"
#       KC_PROXY: edge
#       KC_HOSTNAME: localhost
#       KC_FEATURES: preview
#       # Configuration du plugin HTTP Event Listener
#       KC_SPI_EVENTS_LISTENER_HTTP_EVENT_LISTENER_ENABLED: "true"
#       KC_SPI_EVENTS_LISTENER_HTTP_EVENT_LISTENER_EVENTS: "LOGIN,REGISTER,UPDATE_PROFILE,DELETE_ACCOUNT"
#       KC_SPI_EVENTS_LISTENER_HTTP_EVENT_LISTENER_URI: "http://localhost:2000/api/users/sync"
#       # KC_SPI_EVENTS_LISTENER_HTTP_USERNAME: ""
#       # KC_SPI_EVENTS_LISTENER_HTTP_PASSWORD: ""
#       # KC_SPI_EVENTS_LISTENER_HTTP_TOPIC: "keycloak-events"
#     ports:
#       - "8080:8080"
#     depends_on:
#       postgres:
#         condition: service_healthy
#     command: 
#       - "start-dev"
#       - "--spi-events-listener-http-event-listener-enabled=true"
#       - "--spi-events-listener-http-event-listener-uri=http://localhost:2000/api/users/sync"
#     networks:
#       - dcat_network

# volumes:
#   postgres_data:

# networks:
#   dcat_network:
#     driver: bridge


