# name: Build and deploy

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build and deploy
#         run: |
#           docker-compose build
#           docker-compose up -d



name: Build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Docker environment
        run: |
          echo "Current Docker environment variables:"
          env | grep DOCKER
          
      - name: Try to reset Docker environment
        run: |
          unset DOCKER_HOST
          unset DOCKER_TLS_VERIFY
          unset DOCKER_CERT_PATH
          
      - name: Build and deploy
        run: |
          docker-compose build
          docker-compose up -d
