# name: Build and deploy

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build and deploy
#         run: |
#           docker-compose build
#           docker-compose up -d



# name: Build and deploy

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Debug environment
#         run: |
#           # Check Docker installation
#           which docker || echo "Docker binary not found"
#           which docker-compose || echo "Docker Compose binary not found"
          
#           # Check versions
#           docker --version || echo "Docker command failed"
#           docker-compose --version || echo "Docker Compose command failed"
          
#           # Check if Docker daemon is running
#           docker info || echo "Docker daemon not accessible"
          
#           # Check Docker socket
#           ls -la /var/run/docker.sock || echo "Docker socket not found at default location"
          
#           # Check user permissions
#           id
#           groups
          
#           # Check Docker group
#           getent group docker || echo "Docker group not found"

#       - name: Try alternate Docker Compose approach
#         run: |
#           # Try using Docker CLI plugin (v2 compose)
#           docker compose version || echo "Docker Compose plugin not available"
          
#           # Check Python environment
#           python3 --version
#           pip3 list | grep -E "docker|compose|urllib3|requests"



name: Build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, '[deploy]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show commit message
        run: echo "Deploying based on commit message: ${{ github.event.head_commit.message }}"
      
      - name: Build and deploy
        run: |
          echo "Starting deployment..."
          docker-compose build
          docker-compose up -d
          echo "Deployment completed!"

