# name: Build and deploy

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build and deploy
#         run: |
#           docker-compose build
#           docker-compose up -d



name: Build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker socket
        run: |
          # Ensure Docker socket is accessible
          sudo chmod 666 /var/run/docker.sock || true
          
      - name: Build and deploy
        run: |
          DOCKER_HOST=unix:///var/run/docker.sock docker-compose build
          DOCKER_HOST=unix:///var/run/docker.sock docker-compose up -d

