name: Build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          docker-compose build
          docker-compose up -d
